app_front:
    resource: "@AppFrontBundle/Resources/config/routing.yml"
   
jstranslations:
    resource: "@FunddyJsTranslationsBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation