<?php

namespace App\FrontBundle\Entity;

/**
 * LoginfailureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginfailureRepository extends \Doctrine\ORM\EntityRepository
{
	public function getRecentFailures($user, $ip)
	{
		$start = new \DateTime('now');
		$start->sub(new \DateInterval("PT30M"));
		$end = new \DateTime('now');

	    $qb = $this->getEntityManager()->createQueryBuilder();
	    $qb->select('lf')
	        ->from('App\FrontBundle\Entity\Loginfailure', 'lf')
	        ->where('lf.user = :user')
	        ->andWhere('lf.ip = :ip')
	        ->andWhere('lf.failedOn >= :start')
	        ->andWhere('lf.failedOn <= :end')
	        ->setParameters(array('user' => $user, 'start' => $start, 'end' => $end, 'ip' => $ip));

	    return $qb->getQuery()->getArrayResult();
	}

	public function removeFailures($user, $ip)
	{
	    $qb = $this->getEntityManager()->createQueryBuilder();
	    $qb->delete('App\FrontBundle\Entity\Loginfailure', 'lf')
	        ->where('lf.user = :user')
	        ->andWhere('lf.ip = :ip')
	        ->setParameters(array('user' => $user, 'ip' => $ip));

	    return $qb->getQuery()->execute();
	}
}
 