<?php

namespace App\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface
{
    public function loadUserByApikey($apiKey)
    {
        return $this->findOneBy(array("apikey" => $apiKey));
    }
    
    public function loadUserByUsername($username){
        return $this->findOneBy(array("username" => $username));
    }

    public function findUserByUsername($username){
        return $this->findOneBy(array("username" => $username));
    }

    public function refreshUser(UserInterface $user){
        if (!$user instanceof User) {   
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_class($user)));
        }

        return $this->loadUserByUsername($user->getUsername());
    }

    public function supportsClass($class){
        return ($class === 'App\FrontBundle\Entity\User');
    }
}
