<?php

namespace App\FrontBundle\Entity;

/**
 * UserlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserlockRepository extends \Doctrine\ORM\EntityRepository
{
	/*
	 * Remove 30 minutes expired user locks	
	 */
	public function removeExpiredlocks()
	{
		$datetime = new \DateTime('now');
		$datetime->sub(new \DateInterval("PT30M"));

	    $qb = $this->getEntityManager()->createQueryBuilder();
	    $qb->delete('App\FrontBundle\Entity\Userlock', 'ul')
	        ->where('ul.lockedOn <= :datetime')
	        ->setParameters(array('datetime' => $datetime));

	    return $qb->getQuery()->execute();
	}
}
